### ISSUE TITLE
 reflectivity.github.io/_includes/footer_content.html provides invalid link to source

### ISSUE THREAD

**Issue by jwuttke** [reflectivity/reflectivity.github.io#10]
See e.g. the broken GitHub link near the bottom of https://www.reflectometry.org/projects/file_formats/text-rep/

**Comment by bmaranville** [comment]
Is there a reason for the trailing slash on the permalink for that URL?  Without that slash, I think the scheme in the footer would work, and since text-rep is not a directory I'm not sure why it would get a slash

**Comment by arm61** [comment]
The reason is that I added the code yesterday when I was annoyed at editing pages and I forgot to account for `index.html` and `index.md`. Hopefully it will be fixed soon (ie. when the ORSO workshop is over and I can remember how Jekyll works.

**Comment by wpotrzebowski** [comment]
I've been trying to fix it in jekyll template but since we are not using same template for all pages (e.g. workshops/index.md or Tuesday.md) it is bit tricky to use the same pattern. Maybe this is something that can be fixed with conditionals https://idratherbewriting.com/documentation-theme-jekyll/mydoc_conditional_logic.html?

**Comment by arm61** [comment]
I am fairly sure that I have resolved this now. I am gonna close this but please reopen if other pages that don't work are found.
